# We will define our chess noun constants here
BEGINNER = 1
INTERMEDIATE = 2
ADVANCED = 3

WHITE_WINS = 0
BLACK_WINS = 1
DRAW = 2

NO_NAME = "None"
BYE_NAME = "Bye"
DEFAULT_FIRST_PLAYER_NAME = "John Smith"
DEFAULT_SECOND_PLAYER_NAME = "Jane Smith"

STANDARD_GAME_TIME = 10
STANDARD_GAME_GAP_TIME = 5
STANDARD_EVENT_LENGTH = 120
STANDARD_PLAYOFF_LENGTH = 20